name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install and build frontend
      - run: npm --prefix frontend ci
      - run: npm --prefix frontend run build

      # Install functions deps and build
      - run: npm --prefix functions ci
      - run: npm --prefix functions run build

      # Deploy to Firebase
      - uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
